server:
  port: 8080
spring:
  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver-default.homelab.tap.fynesy.com/eureka/
      #defaultZone: http://localhost:8080/eureka/
